### ISSUE TITLE
Format Go buffer on write clears file on syntax error

### ISSUE THREAD

**Issue by fvosberg** [Carpetsmoker/dotfiles#2]
Hi arp242,

thanks for sharing you dotfiles and gopher.vim with the community. I really like the approach, so I switched. It's weird to file an issue on you personal dotfiles, but as I'm not too much into vim and Bash, I thought you might know the answer to my problem. 

I've copied the following func from your .vimrc (plugins.vim)

```
    " Format buffer on write.
    au BufWritePre *.go
                \  let s:save = winsaveview()
                \| exe 'keepjumps %!goimports 2>/dev/null || cat /dev/stdin'
                \| call winrestview(s:save)
```

Whenever I have  syntax error in my files, it clears the file, because goimports doesn't print any to stdout. Is the `|| cat /dev/stdin` supposed to fix that edge case, or don't you bother? Any idea to fix that? I'm not sure how to `:h` for that. Maybe there is something like "only replace buffer content, when return == 0.

Thanks in advance

**Comment by arp242** [comment]
> Is the `|| cat /dev/stdin` supposed to fix that edge case, or don't you bother?

Yeah, if `goimports` has an error then print the input to the program (which is the original source code).

It works on my Linux system; I'm not sure why it doesn't for you. `/dev/stdin` should be present on pretty much all Unix-y systems as far as I can find. Maybe it behaves different on some (e.g. can only read once)?

You can do it in VimScript, it's just less concise and doing a fully side-effect free "replace buffer contents" is also somewhat non-trivial.

This method isn't perfect either, since undo isn't handled properly, errors aren't shown, etc. Come to think of it, maybe there's some room for a small minimalist "replace buffer contents on write"-plugin :thinking:

**Comment by fvosberg** [comment]
Hi, thanks for your fast reply. I'm using OSX, that might be the cause of the problem. 

Is there a way I can try to read multiple times from /dev/stdin without vim? To narrow the problem down. Like a command which shows, that you can read multiple times from /dev/stdin and I don't. When does stdin get cleared? When the bash process exits?

Even googling for "reading multiple times from /dev/stdin" doesn't yield any good results. It's driving me nuts.

Many thanks!

**Comment by fvosberg** [comment]
Should this script has another output?

```
$ echo "foobar" | bash -c 'cat /dev/stdin; cat /dev/stdin; echo "end"'
foobar
end
```

**Comment by fvosberg** [comment]
And can you maybe try the following command with a valid and an invalid file?

`cat hello.go | bash -c 'goimports 2>/dev/null || cat /dev/stdin'`

The latter produces no output on my OSX machine and no output on a machine of a friend of mine, who runs on Archlinux

Thanks!

**Comment by arp242** [comment]
The command that Vim runs (slightly abbreviated) is:

    (goimports 2>/dev/null || cat /dev/stdin) < hello.go 2>&1

The trick is that that `( .. )` start a subshell, and stdin is fed to that.

You can verify the command that Vim runs by running it with `:verbose` like so:

    :20verbose %!goimports 2>/dev/null || cat /dev/stdin

**Comment by fvosberg** [comment]
Hi,

thanks Martin, I’ll verify that tomorrow. But bash -c starts a sub shell as well, doesn’t it? 

I’ll check it though, thanks!

**Comment by arp242** [comment]
Well, it starts a new shell, but does something different since the redirection is different.

**Comment by fvosberg** [comment]
Hi thanks for the answer, didn't expect a different behaviour.

I tried the following:

```
$ echo "foobar" > aa
$ (cat /dev/stdin; cat /dev/stdin; echo "end") < aa
foobar
end
```

which showed, that it's indeed only possible to read once from stdin on my computer. A friend of mine, who is running on Arch experienced the same, though. I'll try to hack a workaround with tee and a tmp-File.

Although I'm interested if the above code is producing the same output on your computer, to narrow the poblem down and double check it.

**Comment by fvosberg** [comment]
Ou, sorry, this was a communication problem. The arch friend gets 

> foobar
> foobar
> end

We got it and you were right. Thanks a lot.

**Comment by arp242** [comment]
Yeah, I'm using Arch Linux too. So now that we know what the problem is, need to think what a good solution is. I'll try and <s>steal</s> borrow my housemate's macbook so I can experiment some this week.

**Comment by fvosberg** [comment]
Hi Martin,

for know I'm trying ale, which comes with a formatting function. I've tinkered a little bit around with a bash command and tmp files, but it didn't work out. Maybe I'll try to go more vanilla. Thanks a lot

Keep up with the good work, I love gopher.vim
